#ifndef _PARAMETERS_HPP_
#define _PARAMETERS_HPP_

#define GAUSSIAN_KERNEL_PARAM   40
#define NUM_SAMPLED_POINTS      20
#define OPTIMIZATION_PRECISION  0.0000001
#define OPTIMIZATION_MAX_ITER   100000

#endif
